Add livewire component discovery solution.
facade/ignition pull request #319
Opened 2020-10-03 18:46 UTC by ZeProf2Code

2020-10-05 06:32 UTC, freekmurze requested changes
Looks good, just a few nitpicks. Could you add a screenshot in the comments of how this solution looks like? Thanks!

2020-10-05 06:32 UTC, freekmurze commented on src/SolutionProviders/MissingLivewireComponentSolutionProvider.php
> +        }
Also check here if the class `Livewire\LivewireComponentsFinder` exists.

2020-10-05 06:32 UTC, freekmurze commented on src/SolutionProviders/MissingLivewireComponentSolutionProvider.php
> +        if (! $throwable instanceof \Livewire\Exceptions\ComponentNotFoundException) {
Import this class

2020-10-09 17:14 UTC, ZeProf2Code commented
![image](https://user-images.githubusercontent.com/32982428/95612439-acad2300-0a63-11eb-984f-80d588d3ef15.png)
How it looks ^

2020-10-14 08:21 UTC, merged

2020-10-14 08:21 UTC, freekmurze commented
Thank you!