Fix MakeViewVariableOptionalSolution to disallow stream wrappers and files that do not end in .blade.php
facade/ignition pull request #334
Opened 2020-11-16 11:16 UTC by cfreal

Hello, as discussed by email, this fixes a serious vulnerability.
Hopefully my code is OK-ish.

2020-11-17 07:19 UTC, freekmurze requested changes

2020-11-17 07:19 UTC, freekmurze commented on src/Solutions/MakeViewVariableOptionalSolution.php
> +        if (!Str::startsWith($parameters['viewFile'], ['/', './']) || !Str::endsWith($parameters['viewFile'], '.blade.php')) {
Wrap this code up in a function.  `isSafePath` and break up the conditional to use early returns.
Example: https://spatie.be/videos/readable-laravel/refactor-complex-conditionals

2020-11-17 09:18 UTC, merged

2020-11-17 09:18 UTC, freekmurze commented
Thanks!

2021-01-13 08:02 UTC, abergmann commented
[CVE-2021-3129](https://nvd.nist.gov/vuln/detail/CVE-2021-3129) was assigned to this PR.

2021-01-28 21:08 UTC, jplana-ubc commented
Can we get this patch committed to the 1.16.x branch?

2021-01-28 22:58 UTC, jplana-ubc commented
I would love to create a PR myself with the changes for the 1.16.4 release, but unfortunately everything lives in the same branch (both 2.x and 1.x versions of this package).

It would be fantastic if there was a way to push these changes to a 1.16.5 tag, so all the folks still using Laravel 6 and facade/ignition 1.x could benefit of this change.

`diff --git a/src/Solutions/MakeViewVariableOptionalSolution.php b/src/Solutions/MakeViewVariableOptionalSolution.php
index 2903414..7e53117 100644
--- a/src/Solutions/MakeViewVariableOptionalSolution.php
+++ b/src/Solutions/MakeViewVariableOptionalSolution.php
@@ -4,6 +4,7 @@ namespace Facade\Ignition\Solutions;

 use Facade\IgnitionContracts\RunnableSolution;
 use Illuminate\Support\Facades\Blade;
+use Illuminate\Support\Str;

 class MakeViewVariableOptionalSolution implements RunnableSolution
 {
@@ -71,8 +72,24 @@ class MakeViewVariableOptionalSolution implements RunnableSolution
         }
     }

+    protected function isSafePath(string $path): bool
+    {
+        if (!Str::startsWith($path, ['/', './'])) {
+            return false;
+        }
+        if (!Str::endsWith($path, '.blade.php')) {
+            return false;
+        }
+
+        return true;
+    }
+
     public function makeOptional(array $parameters = [])
     {
+        if (!$this->isSafePath($parameters['viewFile'])) {
+            return false;
+        }
+
         $originalContents = file_get_contents($parameters['viewFile']);
         $newContents = str_replace('$'.$parameters['variableName'], '$'.$parameters['variableName']." ?? ''", $originalContents);
`