facade/ignition#302: Fix memory leaks caused by log and query recorder
facade/ignition pull request #344
Opened 2021-01-17 14:48 UTC by TheLevti

- Add optional log recorder limit to prevent memory leaks. Especially
  noticable during long running tasks or daemons.
- Rewrote query recorder to not tigthly couple it with the framework
  container when deciding whether to include bindings or limit the
maximum query count that is recorded.
- Added a config flag to disable log recording all together.
- Made sure that query and log recorders are not used when their enable
  flag is disabled.

Closes #302

Closes #301

2021-01-17 14:55 UTC, freekmurze commented
On first sight, this seems ok to me. 

@AlexVanderbist can you review and merge this?

2021-02-03 07:49 UTC, freekmurze requested changes

2021-02-03 07:49 UTC, freekmurze commented on CHANGELOG.md
> +
We don't want to maintain these links, could you remove them?

2021-02-04 07:58 UTC, rubenvanassche requested changes
Some minor changes request, but a great PR, look forward to merge it!

2021-02-04 07:58 UTC, rubenvanassche commented on src/IgnitionServiceProvider.php
> +        if (config('flare.reporting.report_queries')) {
Could you add some room between these statements? It feels a  bit crammed up here.

2021-02-04 07:58 UTC, rubenvanassche commented on src/IgnitionServiceProvider.php
> +            $middlewares[] = AddQueries::class;
Same here, some room between these statements will make them more readable

2021-02-04 07:58 UTC, rubenvanassche commented on CHANGELOG.md
> +## [2.5.6] - 2020-12-29
Could you change the changelog 😄 to the format is was before? Like this:

```
## VERSION - DATE
-THING THAT CHANGED
```

Otherwise we lose consistency between our packages

2021-02-04 11:17 UTC, AlexVanderbist approved these changes
Apart from the minor remarks by my colleagues; LGTM!

2021-02-04 19:45 UTC, TheLevti commented on CHANGELOG.md
> +## [2.5.6] - 2020-12-29
Sure, was just a habit and suggestion to use a standardized format.

2021-02-04 19:55 UTC, TheLevti commented on src/IgnitionServiceProvider.php
> +            $middlewares[] = AddQueries::class;
done

2021-02-04 19:55 UTC, TheLevti commented on src/IgnitionServiceProvider.php
> +        if (config('flare.reporting.report_queries')) {
done

2021-02-04 19:55 UTC, TheLevti commented on CHANGELOG.md
> +
removed changelog changes

2021-02-05 12:51 UTC, rubenvanassche commented
Thanks, looks great!

2021-02-05 12:51 UTC, merged

2021-02-13 14:11 UTC, rimace commented
This change is causing a memory leak for me.
I am importing ~300,000 models. First 1,000 models are read and bundled into one transaction, then the query is fired and then next 1,000 and so on.
Usually my import uses always around 25 MB RAM, but since version 2.5.11 my importer reaches 500 MB RAM after a while.
Will report a proper issue with an example later today.

2021-02-14 12:01 UTC, TheLevti commented
> This change is causing a memory leak for me.
> I am importing ~300,000 models. First 1,000 models are read and bundled into one transaction, then the query is fired and then next 1,000 and so on.
> Usually my import uses always around 25 MB RAM, but since version 2.5.11 my importer reaches 500 MB RAM after a while.
> Will report a proper issue with an example later today.

Thanks for the feedback. Please let me know the details. For my use case the memory leak that I had previously was fixed once the array is topping out at the configured limit.

2021-02-14 12:12 UTC, rimace reviewed
That's it.
The QueryRecorder uses a new config which didn't exist in my config cache (forgot to recreate it).
Because QueryRecorder was activated but the maximum_number_of_collected_logs didn't exist in my config cache yet, it was null which deactivated the "maximum logs" of 200 (by default).
So it was my fault for not recreating the config cache. Still I think the name of the config variable is wrong there.

2021-02-14 12:38 UTC, TheLevti commented on src/IgnitionServiceProvider.php
> +                $app->get('config')->get('flare.reporting.maximum_number_of_collected_logs')
Oh jeez, this is the classic copy pasta mistake. Will provide a fix for it.

2021-02-14 12:46 UTC, TheLevti commented on src/IgnitionServiceProvider.php
> +                $app->get('config')->get('flare.reporting.maximum_number_of_collected_logs')
https://github.com/facade/ignition/pull/354